language: c
compiler:
    - gcc
sudo: required
services:
    - docker
git:
    depth: false
notifications:
    email:
        recipients:
            - compute-runtime@intel.com
matrix:
    include:
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-18.04 COMPILER=clang-8
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-18.04 COMPILER=clang-8-l0
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc GEN=gen-8
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc GEN=gen-9
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc GEN=gen-11
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc GEN=gen-12
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc GEN=gen-9-l0
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc GEN=gen-11-l0
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc GEN=gen-12-l0
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-20.04 COMPILER=clang
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-20.04 COMPILER=clang-l0
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-20.04 COMPILER=gcc GEN=gen-8
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-20.04 COMPILER=gcc GEN=gen-9
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-20.04 COMPILER=gcc GEN=gen-11
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-20.04 COMPILER=gcc GEN=gen-12
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-20.04 COMPILER=gcc GEN=gen-9-l0
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-20.04 COMPILER=gcc GEN=gen-11-l0
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-20.04 COMPILER=gcc GEN=gen-12-l0


script: ./scripts/run-build.sh

