language: c
compiler:
    - gcc
sudo: required
services:
    - docker
git:
    depth: false
notifications:
    email:
        recipients:
            - compute-runtime@intel.com
matrix:
    include:
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-16.04 COMPILER=gcc-5
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-16.04 COMPILER=clang-4
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-16.04 COMPILER=clang-5
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-18.04 COMPILER=clang-4
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-18.04 COMPILER=clang-5
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-18.04 COMPILER=clang-6
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-18.04 COMPILER=clang-7
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc-5
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc-6
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc-7 GEN=gen-8
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc-7 GEN=gen-9

script: ./scripts/run-build.sh

