components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-20.1.1
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: f1e279a30faaa77be51085d69360da8182ca57e3
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: 17880d95ecf40e6eefccc8f2db370e22b8e3a400
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 9569d817efd31ae89115e6f8d57cf23231e439a6
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 57e0a77511edfc4ca0e42b939075d1ab23c48a09
    type: git
  level_zero:
    branch: master
    dest_dir: level_zero
    repository: https://github.com/oneapi-src/level-zero
    revision: v0.91
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: a8173734bcadfb652dee6fef242e7634de9220d8-1390
converter: M-1396
version: '1'
