components:
  gmmlib:
    clean_on_sync: true
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-19.4.1
    repository: https://github.com/intel/gmmlib.git
  igc:
    clean_on_sync: true
    dest_dir: igc
    type: git
    branch: igc
    revision: 510938ce77351f6e8ae92dcd37080b542b7a9e68
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: 48939fe5ad2ee4d08c1d78649627fa69b0e12475
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: eb8b7dc04959f205c50df8bf2fe1532d0171bc5a
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 117d709602a49f4aae6e7965743cec61834a3c35
    type: git
  libva:
    clean_on_sync: true
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    clean_on_sync: true
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 39ec79c0ca347796daa7b07fbb81dd1bf45ccad5-1355
converter: M-1355
version: '1'
