components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: e52096b67adeba76c76007a00924b76152a3f5d6
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: 9508c9a18b964d500d7e343e081dd4213a590cb7
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: 768f03c23ce7f7fd6a13c8dca975b6245f97b354
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 170916ffe6a2acaed65aa2b59c5c1b9993037c21
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 70be2c96ab6a6ddbd8987b89f8818a6a0858ffdd
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 790647-1082
    type: git
converter: M-1097
version: '1'
