components:
  aub_stream:
    branch: master
    dest_dir: aub_stream
    repository: https://github.com/intel/aubstream
    revision: 192d584f728bfb355e30a2df87ebaf538445f485
    type: git
  gmmlib:
    dest_dir: gmmlib
    type: git
    asset_name: gmmlib
    branch: master
    revision: intel-gmmlib-22.3.0
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    asset_name: igc
    branch: master
    revision: ac4405f0575e0a381788fe41558fa10498745377
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    dest_dir: igsc
    type: git
    asset_name: igsc
    branch: master
    revision: V0.8.7
    repository: https://github.com/intel/igsc.git
  infra:
    branch: master
    dest_dir: infra
    fetch_tags: true
    revision: v4768
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kernels_bin:
    dest_dir: kernels_bin
    type: git
    branch: kernels_bin
    revision: 2039-615
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: aabe0b3ad02a9d40cc44046ddb4ee232382ba776
    type: git
  level_zero:
    dest_dir: level_zero
    type: git
    branch: master
    revision: v1.9.9
    repository: https://github.com/oneapi-src/level-zero
  libva:
    dest_dir: libva
    type: git
    asset_name: libva
    branch: master
    revision: 2.2.0
    repository: https://github.com/intel/libva.git
  metrics-discovery:
    dest_dir: metrics/discovery
    type: git
    asset_name: metrics-discovery
    branch: master
    revision: metrics-discovery-1.12.163
    repository: https://github.com/intel/metrics-discovery.git
  metrics-library:
    dest_dir: metrics/library
    type: git
    asset_name: metrics-library
    branch: master
    revision: metrics-library-1.0.133
    repository: https://github.com/intel/metrics-library.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 42e0debbf60967df636a7eb2f0264861b4e5ed6a-2039
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-2039
version: '1'
