components:
  aub_stream:
    branch: master
    dest_dir: aub_stream
    repository: https://github.com/intel/aubstream
    revision: d6d6aaf5b249d33b319f2086860255a02c9ae108
    type: git
  gmmlib:
    asset_name: gmmlib
    dest_dir: gmmlib
    type: git
    branch: master
    revision: intel-gmmlib-22.3.19
    repository: https://github.com/intel/gmmlib.git
  igc:
    asset_name: igc
    dest_dir: igc
    type: git
    branch: releases/igc-1.0.16900
    revision: 869ae8ac6cf78582b1dae4d47c237843dd8817e9
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    asset_name: igsc
    dest_dir: igsc
    type: git
    branch: master
    revision: V0.8.16
    repository: https://github.com/intel/igsc.git
    component_version: 230
  infra:
    branch: master
    dest_dir: infra
    fetch_tags: true
    revision: v6041
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kernels_bin:
    dest_dir: kernels_bin
    type: git
    branch: kernels_bin
    revision: 2441-1792
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 68cfaf9eba1360f05d06b14d19389310b86c4dd9
    type: git
  level_zero:
    asset_name: level_zero
    dest_dir: level_zero
    type: git
    branch: master
    revision: v1.17.6
    repository: https://github.com/oneapi-src/level-zero
  libva:
    asset_name: libva
    dest_dir: libva
    type: git
    branch: v2.2-branch
    revision: 2.2.0
    repository: https://github.com/intel/libva.git
  metrics-discovery:
    asset_name: metrics-discovery
    dest_dir: metrics/discovery
    type: git
    branch: master
    revision: metrics-discovery-1.12.171
    repository: https://github.com/intel/metrics-discovery.git
  metrics-library:
    asset_name: metrics-library
    dest_dir: metrics/library
    type: git
    branch: master
    revision: metrics-library-1.0.161
    repository: https://github.com/intel/metrics-library.git
  neo-clang-format:
    dest_dir: tools/clang-format
    type: git
    branch: clang-format
    revision: 15.0.6
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 71477e0cc69901cda46f0f899dddbbb14576f79a-2441
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-2441
version: '1'
