components:
  aub_stream:
    branch: master
    dest_dir: aub_stream
    repository: https://github.com/intel/aubstream
    revision: b43642731e5e37e4877af930f7a8cf9f834940d6
    type: git
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-22.3.0
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: d336f5fd32a32934d334c18214a9ebcbd4aa9753
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    dest_dir: igsc
    type: git
    branch: igsc
    revision: V0.8.6
    repository: https://github.com/intel/igsc.git
  infra:
    branch: master
    dest_dir: infra
    fetch_tags: true
    revision: v4649
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kernels_bin:
    dest_dir: kernels_bin
    type: git
    branch: kernels_bin
    revision: 2024-543
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 6fb5226219fa8b16dc6b67db06a8e7bc7c5ba8e4
    type: git
  level_zero:
    dest_dir: level_zero
    type: git
    branch: master
    revision: v1.9.4
    repository: https://github.com/oneapi-src/level-zero
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: 2.2.0
    repository: https://github.com/intel/libva.git
  metrics-discovery:
    dest_dir: metrics/discovery
    type: git
    branch: metrics-discovery
    revision: metrics-discovery-1.12.160
    repository: https://github.com/intel/metrics-discovery.git
  metrics-library:
    dest_dir: metrics/library
    type: git
    branch: metrics-library
    revision: metrics-library-1.0.122
    repository: https://github.com/intel/metrics-library.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 0262f03a59f8acef3a308d9b0d38465b4b82a017-2024
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-2024
version: '1'
