components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: 375036ac3596ca9f55d2a070bac4bcffbf3fa7fd
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: a56f313c2f50da77a086ee009bc68e277fe3c1e9
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: d5f8dc81d045ebdc43f636f21c910ea22931eb69
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: b884c2457536e0ec654f54bcc9292c20ffcb6367
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 99402337f2b42a058a1b20cb0dc130033fdbd65f
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 775910-972
    type: git
converter: M-975
version: '1'
