components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: intel-gmmlib-19.1.1
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: ebfc688126900a821e407a96417800919b793447
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: 2c759bb47b52dc36912ce67f2e8ef82f86b871dd
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 703062a489dd885a09678592a3a9a144bab53620
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: b485c17a305407d9f57bc0533af34675af0bc9ff
    type: git
  libva:
    branch: libva
    clean_on_sync: true
    dest_dir: libva
    repository: https://github.com/intel/libva.git
    revision: c9bb65b
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 0dea8bf00d710a5d2da5d04eb5ae595d0df4ce47-1217
    type: git
converter: M-1244
version: '1'
