components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-20.1.1
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: 97ba4199cf934fc6aee61d244188af522ae7d7c7
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: 9759640da5ae63f175bd60216b5b7aa5d54ac5eb
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 9569d817efd31ae89115e6f8d57cf23231e439a6
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 57e0a77511edfc4ca0e42b939075d1ab23c48a09
    type: git
  level_zero:
    branch: master
    dest_dir: level_zero
    repository: https://github.com/oneapi-src/level-zero
    revision: v0.91
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 3232e5d67b5c3dd2323f13bede3ab1558b5aa4b9-1401
converter: M-1401
version: '1'
