components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: 40b45bd6109a6a485b4a721686fc32ba7307a548
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: 65bbbe3ea8afb2d40ef759a51a358b4795860ce0
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: 4e937dffeda356f6334f4c84a07a353fc8c0c7af
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 3cfa5d871d87af24ef422ac062e7d436aa09be79
    type: git
  khronos:
    branch: master
    clean_on_sync: true
    dest_dir: khronos
    repository: https://github.com/KhronosGroup/OpenCL-Headers.git
    revision: de26592167b9fdea503885e40e8755393c56523d
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: 99402337f2b42a058a1b20cb0dc130033fdbd65f
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 769497-961
    type: git
converter: M-961
version: '1'
