components:
  aub_stream:
    branch: master
    dest_dir: aub_stream
    repository: https://github.com/intel/aubstream
    revision: e51dfa54e20e30af74baba60ab4bcf385eb3246d
    type: git
  gmmlib:
    asset_name: gmmlib
    dest_dir: gmmlib
    type: git
    branch: master
    revision: intel-gmmlib-22.3.11
    repository: https://github.com/intel/gmmlib.git
  igc:
    asset_name: igc
    dest_dir: igc
    type: git
    branch: releases/igc-1.0.15985
    revision: da8492a4a8f80c7d2aa69cc8bc072bd2ad488937
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    asset_name: igsc
    dest_dir: igsc
    type: git
    branch: master
    revision: V0.8.16
    repository: https://github.com/intel/igsc.git
    component_version: 208
  infra:
    branch: master
    dest_dir: infra
    fetch_tags: true
    revision: v5705
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kernels_bin:
    dest_dir: kernels_bin
    type: git
    branch: kernels_bin
    revision: 2262-1272
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 552a3276a44e3255cf2a184acfc98123a43518b6
    type: git
  level_zero:
    asset_name: level_zero
    dest_dir: level_zero
    type: git
    branch: master
    revision: v1.15.8
    repository: https://github.com/oneapi-src/level-zero
  libva:
    asset_name: libva
    dest_dir: libva
    type: git
    branch: v2.2-branch
    revision: 2.2.0
    repository: https://github.com/intel/libva.git
  metrics-discovery:
    asset_name: metrics-discovery
    dest_dir: metrics/discovery
    type: git
    branch: master
    revision: metrics-discovery-1.12.170
    repository: https://github.com/intel/metrics-discovery.git
  metrics-library:
    asset_name: metrics-library
    dest_dir: metrics/library
    type: git
    branch: master
    revision: metrics-library-1.0.156
    repository: https://github.com/intel/metrics-library.git
  neo-clang-format:
    dest_dir: tools/clang-format
    type: git
    branch: clang-format
    revision: 15.0.6
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 8ef787b722f9da2fcd0fe5faa1b7202b8c16e45a-2243
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-2262
version: '1'
