components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-19.4.1
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: fcfd6f6bd2b510250f3801f4c940e82579e841ca
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: dfafb3ee04266e9e77a53360d700553e7973b677
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 339c0793eac1102c50f00346bbf88f2013f856c7
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 710b620b08792ba0367bcabd54c479ede7518603
    type: git
  level_zero:
    branch: master
    dest_dir: level_zero
    repository: https://github.com/oneapi-src/level-zero
    revision: v0.91
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: a8173734bcadfb652dee6fef242e7634de9220d8-1390
converter: M-1390
version: '1'
