components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-22.1.3
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: d83afa249b6f297b40c9266020a8b3736b2c193b
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    dest_dir: igsc
    type: git
    branch: igsc
    revision: V0.6.0
    repository: https://github.com/intel/igsc.git
  infra:
    branch: master
    dest_dir: infra
    revision: bc1736dc68a889190ea1503c86447ee7775769b5
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kernels_bin:
    dest_dir: kernels_bin
    type: git
    branch: kernels_bin
    revision: 1907-188
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: c9a9f1c0d46f51b116cd9cb562205b20d33539ed
    type: git
  level_zero:
    dest_dir: level_zero
    type: git
    branch: master
    revision: v1.8.1
    repository: https://github.com/oneapi-src/level-zero
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 4f190cb73994e6967c913fc0e08624fa31c0c14c-1902
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-1907
version: '1'
